In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [7]:
#Load Libraries for Data Analysis
import pandas as pd
import os
os.listdir('/kaggle/input/datasets/corneliusozoji/salesreport')

['My Sales.csv']

In [9]:
# Load the dataset
data = pd.read_csv("/kaggle/input/datasets/corneliusozoji/salesreport/My Sales.csv")

# Display the first 10 rows
data.head(10)

   Open  High  Low  Close  Volume
0   100   105   98    104    1500
1   104   108  102    107    1800
2   107   110  105    109    2100
3   109   112  108    111    2500
4   111   115  110    114    2700
5   114   118  113    117    3000
6   117   120  116    119    3200
7   119   123  118    122    3500
8   122   126  121    125    3700
9   125   128  123    127    4000

In [10]:
# Check for missing values (True/False)
data.isnull()

    Open   High    Low  Close  Volume
0  False  False  False  False   False
1  False  False  False  False   False
2  False  False  False  False   False
3  False  False  False  False   False
4  False  False  False  False   False
5  False  False  False  False   False
6  False  False  False  False   False
7  False  False  False  False   False
8  False  False  False  False   False
9  False  False  False  False   False

In [11]:
# Counting missing values per column
data.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [12]:
# Total missing values
data.isnull().sum().sum()

np.int64(0)

In [13]:
# Check How Many Records There Are 
data.shape

(10, 5)

In [17]:
# Drop Rows With Missing Values Since Not Much i.e 27
data_clean = data.dropna()

In [ ]:
# Check to see output 
data_clean.isnull().sum()

In [18]:
# Check How Many Records Remain
data_clean.shape

(10, 5)

In [19]:
# Check for Duplicates - Shows True for Duplicate Rows
data_clean.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [20]:
# Check for No of Duplicates 
data_clean.duplicated().sum()

np.int64(0)

In [21]:
# Display first 10 Records
data_clean.head(10)

   Open  High  Low  Close  Volume
0   100   105   98    104    1500
1   104   108  102    107    1800
2   107   110  105    109    2100
3   109   112  108    111    2500
4   111   115  110    114    2700
5   114   118  113    117    3000
6   117   120  116    119    3200
7   119   123  118    122    3500
8   122   126  121    125    3700
9   125   128  123    127    4000

In [25]:
# Display first 8 Records
data_clean.head(10)

   Open  High  Low  Close  Volume
0   100   105   98    104    1500
1   104   108  102    107    1800
2   107   110  105    109    2100
3   109   112  108    111    2500
4   111   115  110    114    2700
5   114   118  113    117    3000
6   117   120  116    119    3200
7   119   123  118    122    3500
8   122   126  121    125    3700
9   125   128  123    127    4000

In [37]:
# Separate features and target
X = data_clean.drop('Open', axis=1)   
y = data_clean['Close']

In [46]:
# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [47]:
# Display the sizes of the splits
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8, 4)
X_test shape: (2, 4)
y_train shape: (8,)
y_test shape: (2,)

In [49]:
from sklearn.linear_model import LinearRegression

# Create the Linear Regression model
model = LinearRegression()

# Train (fit) the model
model.fit(X_train, y_train)

# Display the model coefficients and intercept
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: -0.4999999999994742
Coefficients: [ 5.00000000e-01  3.33066907e-16  5.00000000e-01 -2.08166817e-16]

In [50]:
from sklearn.metrics import r2_score, mean_squared_error
import pandas as pd
import numpy as np

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("R-squared (R²):", r2)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)

# Display model coefficients
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print("\nModel Coefficients:")
print(coefficients)

# Display intercept
print("\nIntercept:", model.intercept_)

R-squared (R²): 1.0
Mean Squared Error (MSE): 3.725947827539883e-26
Root Mean Squared Error (RMSE): 1.9302714388240537e-13

Model Coefficients:
  Feature   Coefficient
0    High  5.000000e-01
1     Low  3.330669e-16
2   Close  5.000000e-01
3  Volume -2.081668e-16

Intercept: -0.4999999999994742